"""Replace fixed pricing engine with generic attribute-driven engine

Revision ID: 10127f091907
Revises: 48eefd5c3ddf
Create Date: 2026-07-28 11:05:05.093386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10127f091907'
down_revision: Union[str, Sequence[str], None] = '48eefd5c3ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)
    op.create_index(op.f('ix_attributes_name'), 'attributes', ['name'], unique=False)
    op.create_table('extra_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('charge_type', sa.Enum('flat', 'per_unit', 'per_sqft', 'percentage', name='chargetype'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extra_charges_id'), 'extra_charges', ['id'], unique=False)
    op.create_index(op.f('ix_extra_charges_name'), 'extra_charges', ['name'], unique=False)
    op.create_table('quantity_slabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantity_slabs_id'), 'quantity_slabs', ['id'], unique=False)
    op.create_table('attribute_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('extra_price', sa.Float(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_options_id'), 'attribute_options', ['id'], unique=False)
    op.create_table('price_matrix_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity_slab_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quantity_slab_id'], ['quantity_slabs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_matrix_cells_id'), 'price_matrix_cells', ['id'], unique=False)
    op.create_table('price_matrix_cell_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_matrix_cell_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('attribute_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['attribute_option_id'], ['attribute_options.id'], ),
    sa.ForeignKeyConstraint(['price_matrix_cell_id'], ['price_matrix_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_matrix_cell_options_id'), 'price_matrix_cell_options', ['id'], unique=False)
    op.create_table('quotation_item_attribute_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_item_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('attribute_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['attribute_option_id'], ['attribute_options.id'], ),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_item_attribute_options_id'), 'quotation_item_attribute_options', ['id'], unique=False)
    op.create_table('quotation_item_extra_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_item_id', sa.Integer(), nullable=True),
    sa.Column('extra_charge_id', sa.Integer(), nullable=True),
    sa.Column('computed_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['extra_charge_id'], ['extra_charges.id'], ),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_item_extra_charges_id'), 'quotation_item_extra_charges', ['id'], unique=False)
    op.create_table('invoice_item_attribute_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('attribute_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['attribute_option_id'], ['attribute_options.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_item_attribute_options_id'), 'invoice_item_attribute_options', ['id'], unique=False)

    # Drop dependents of the old fixed masters BEFORE dropping the master tables themselves.
    op.drop_constraint(op.f('fk_quotation_items_gsm_id'), 'quotation_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotation_items_size_id'), 'quotation_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotation_items_colour_id'), 'quotation_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotation_items_lamination_id'), 'quotation_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotation_items_paper_type_id'), 'quotation_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotation_items_binding_id'), 'quotation_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotation_items_foiling_id'), 'quotation_items', type_='foreignkey')
    op.drop_column('quotation_items', 'paper_type_id')
    op.drop_column('quotation_items', 'foiling_id')
    op.drop_column('quotation_items', 'binding_id')
    op.drop_column('quotation_items', 'size_id')
    op.drop_column('quotation_items', 'lamination_id')
    op.drop_column('quotation_items', 'colour_id')
    op.drop_column('quotation_items', 'gsm_id')
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_lookup'), table_name='pricing_rules')
    op.drop_table('pricing_rules')

    op.drop_index(op.f('ix_gsms_id'), table_name='gsms')
    op.drop_index(op.f('ix_gsms_name'), table_name='gsms')
    op.drop_table('gsms')
    op.drop_index(op.f('ix_paper_types_id'), table_name='paper_types')
    op.drop_index(op.f('ix_paper_types_name'), table_name='paper_types')
    op.drop_table('paper_types')
    op.drop_index(op.f('ix_foiling_types_id'), table_name='foiling_types')
    op.drop_index(op.f('ix_foiling_types_name'), table_name='foiling_types')
    op.drop_table('foiling_types')
    op.drop_index(op.f('ix_sizes_id'), table_name='sizes')
    op.drop_index(op.f('ix_sizes_name'), table_name='sizes')
    op.drop_table('sizes')
    op.drop_index(op.f('ix_colours_id'), table_name='colours')
    op.drop_index(op.f('ix_colours_name'), table_name='colours')
    op.drop_table('colours')
    op.drop_index(op.f('ix_binding_types_id'), table_name='binding_types')
    op.drop_index(op.f('ix_binding_types_name'), table_name='binding_types')
    op.drop_table('binding_types')
    op.drop_index(op.f('ix_lamination_types_id'), table_name='lamination_types')
    op.drop_index(op.f('ix_lamination_types_name'), table_name='lamination_types')
    op.drop_table('lamination_types')

    op.add_column('invoice_items', sa.Column('area_sqft', sa.Float(), nullable=True))
    product_pricing_type_enum = postgresql.ENUM('matrix', 'fixed', 'per_area', name='productpricingtype')
    product_pricing_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('products', sa.Column('pricing_type', product_pricing_type_enum, nullable=True))
    op.execute("UPDATE products SET pricing_type = 'matrix' WHERE pricing_type IS NULL")
    op.add_column('products', sa.Column('fixed_price', sa.Float(), nullable=True))
    op.add_column('quotation_items', sa.Column('area_sqft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_items', sa.Column('gsm_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotation_items', sa.Column('colour_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotation_items', sa.Column('lamination_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotation_items', sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotation_items', sa.Column('binding_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotation_items', sa.Column('foiling_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotation_items', sa.Column('paper_type_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # Recreate the old master tables BEFORE re-adding FKs/pricing_rules that depend on them.
    op.create_table('lamination_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lamination_types_pkey'))
    )
    op.create_index(op.f('ix_lamination_types_name'), 'lamination_types', ['name'], unique=True)
    op.create_index(op.f('ix_lamination_types_id'), 'lamination_types', ['id'], unique=False)
    op.create_table('binding_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('binding_types_pkey'))
    )
    op.create_index(op.f('ix_binding_types_name'), 'binding_types', ['name'], unique=True)
    op.create_index(op.f('ix_binding_types_id'), 'binding_types', ['id'], unique=False)
    op.create_table('colours',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('colours_pkey'))
    )
    op.create_index(op.f('ix_colours_name'), 'colours', ['name'], unique=True)
    op.create_index(op.f('ix_colours_id'), 'colours', ['id'], unique=False)
    op.create_table('sizes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sizes_pkey'))
    )
    op.create_index(op.f('ix_sizes_name'), 'sizes', ['name'], unique=True)
    op.create_index(op.f('ix_sizes_id'), 'sizes', ['id'], unique=False)
    op.create_table('foiling_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('foiling_types_pkey'))
    )
    op.create_index(op.f('ix_foiling_types_name'), 'foiling_types', ['name'], unique=True)
    op.create_index(op.f('ix_foiling_types_id'), 'foiling_types', ['id'], unique=False)
    op.create_table('paper_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('paper_types_pkey'))
    )
    op.create_index(op.f('ix_paper_types_name'), 'paper_types', ['name'], unique=True)
    op.create_index(op.f('ix_paper_types_id'), 'paper_types', ['id'], unique=False)
    op.create_table('gsms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gsms_pkey'))
    )
    op.create_index(op.f('ix_gsms_name'), 'gsms', ['name'], unique=True)
    op.create_index(op.f('ix_gsms_id'), 'gsms', ['id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paper_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gsm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('colour_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['colour_id'], ['colours.id'], name=op.f('pricing_rules_colour_id_fkey')),
    sa.ForeignKeyConstraint(['gsm_id'], ['gsms.id'], name=op.f('pricing_rules_gsm_id_fkey')),
    sa.ForeignKeyConstraint(['paper_type_id'], ['paper_types.id'], name=op.f('pricing_rules_paper_type_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('pricing_rules_product_id_fkey')),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name=op.f('pricing_rules_size_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pricing_rules_pkey'))
    )
    op.create_index(op.f('ix_pricing_rules_lookup'), 'pricing_rules', ['product_id', 'paper_type_id', 'gsm_id', 'size_id', 'colour_id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_id'), 'pricing_rules', ['id'], unique=False)

    op.create_foreign_key(op.f('fk_quotation_items_foiling_id'), 'quotation_items', 'foiling_types', ['foiling_id'], ['id'])
    op.create_foreign_key(op.f('fk_quotation_items_binding_id'), 'quotation_items', 'binding_types', ['binding_id'], ['id'])
    op.create_foreign_key(op.f('fk_quotation_items_paper_type_id'), 'quotation_items', 'paper_types', ['paper_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_quotation_items_lamination_id'), 'quotation_items', 'lamination_types', ['lamination_id'], ['id'])
    op.create_foreign_key(op.f('fk_quotation_items_colour_id'), 'quotation_items', 'colours', ['colour_id'], ['id'])
    op.create_foreign_key(op.f('fk_quotation_items_size_id'), 'quotation_items', 'sizes', ['size_id'], ['id'])
    op.create_foreign_key(op.f('fk_quotation_items_gsm_id'), 'quotation_items', 'gsms', ['gsm_id'], ['id'])
    op.drop_column('quotation_items', 'area_sqft')
    op.drop_column('products', 'fixed_price')
    op.drop_column('products', 'pricing_type')
    op.drop_column('invoice_items', 'area_sqft')
    op.drop_index(op.f('ix_invoice_item_attribute_options_id'), table_name='invoice_item_attribute_options')
    op.drop_table('invoice_item_attribute_options')
    op.drop_index(op.f('ix_quotation_item_extra_charges_id'), table_name='quotation_item_extra_charges')
    op.drop_table('quotation_item_extra_charges')
    op.drop_index(op.f('ix_quotation_item_attribute_options_id'), table_name='quotation_item_attribute_options')
    op.drop_table('quotation_item_attribute_options')
    op.drop_index(op.f('ix_price_matrix_cell_options_id'), table_name='price_matrix_cell_options')
    op.drop_table('price_matrix_cell_options')
    op.drop_index(op.f('ix_price_matrix_cells_id'), table_name='price_matrix_cells')
    op.drop_table('price_matrix_cells')
    op.drop_index(op.f('ix_attribute_options_id'), table_name='attribute_options')
    op.drop_table('attribute_options')
    op.drop_index(op.f('ix_quantity_slabs_id'), table_name='quantity_slabs')
    op.drop_table('quantity_slabs')
    op.drop_index(op.f('ix_extra_charges_name'), table_name='extra_charges')
    op.drop_index(op.f('ix_extra_charges_id'), table_name='extra_charges')
    op.drop_table('extra_charges')
    op.drop_index(op.f('ix_attributes_name'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
