"""Add quotation and quotation_items tables

Revision ID: 1bab961191b5
Revises: 79e5c16ffacc
Create Date: 2026-07-27 19:16:34.500394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bab961191b5'
down_revision: Union[str, Sequence[str], None] = '79e5c16ffacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op. Despite the filename, this migration's only real content was a
    duplicate `create_table('customers', ...)` -- an artifact of being
    autogenerated back when the true first migration (79e5c16ffacc) was an
    empty stub, so the tool thought `customers` didn't exist yet. Once
    79e5c16ffacc was filled in to actually create `customers` (see its own
    docstring), this migration's copy became both redundant AND stale (it
    declared `phone` NOT NULL, while the real model -- and 79e5c16ffacc's
    version -- has always had it nullable). Running this against a genuinely
    fresh database after that fix raised `relation "customers" already
    exists`. The actual quotations/quotation_items tables this migration's
    name refers to are created by 7dd0b48d2289, a separate revision later in
    the chain -- this one is kept only so downstream revision IDs don't
    shift."""
    pass


def downgrade() -> None:
    """No-op -- see upgrade()."""
    pass
