"""add role and department to users

Revision ID: 373232cd4694
Revises: dd361ed76923
Create Date: 2026-07-31 09:38:09.316707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373232cd4694'
down_revision: Union[str, Sequence[str], None] = 'dd361ed76923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_role_enum = sa.Enum('admin', 'counter', 'production', 'accounts', name='userrole')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column doesn't create the backing PG enum type by itself - must create it explicitly first.
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', user_role_enum, server_default='counter', nullable=False))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Every pre-existing user got 'counter' from the server_default above; the seeded
    # admin@srijayam.com account (see backend/app/utils/seed.py) needs actual admin rights.
    op.execute("UPDATE users SET role = 'admin' WHERE email = 'admin@srijayam.com'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
    user_role_enum.drop(op.get_bind(), checkfirst=True)
