"""add cash ledger, delivery challan, job card stages, estimate type

Revision ID: 7fd84cc8ae92
Revises: fad51d6558ec
Create Date: 2026-07-31 12:16:14.514470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7fd84cc8ae92'
down_revision: Union[str, Sequence[str], None] = 'fad51d6558ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 'paymentmethod' already exists (created for payments.method in an earlier migration) - reused
# here for purchase_payments.method, so it must NOT try to CREATE TYPE again.
payment_method_enum = postgresql.ENUM('cash', 'upi', 'card', 'credit', 'bank_transfer', 'cheque', name='paymentmethod', create_type=False)
# New in this migration, and used twice (purchase_payments via create_table, payments via
# add_column) - create_type=False on both; the type itself is created explicitly, once, below.
cheque_status_enum = postgresql.ENUM('pending', 'deposited', 'cleared', 'bounced', name='chequestatus', create_type=False)
purchase_payment_status_enum = postgresql.ENUM('unpaid', 'partially_paid', 'paid', name='purchasepaymentstatus', create_type=False)
document_type_enum = postgresql.ENUM('quotation', 'estimate', name='documenttype', create_type=False)
delivery_challan_bill_type_enum = postgresql.ENUM('cash_bill', 'tax_gst_bill', name='deliverychallanbilltype', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    cheque_status_enum.create(bind, checkfirst=True)
    purchase_payment_status_enum.create(bind, checkfirst=True)
    document_type_enum.create(bind, checkfirst=True)
    delivery_challan_bill_type_enum.create(bind, checkfirst=True)
    # 'paymentmethod' already existed (payments.method) without 'cheque' - ADD VALUE extends the
    # existing type in place rather than recreating it. Must run outside the autocommit-disabled
    # block that ALTER TYPE ... ADD VALUE normally requires pre-PG12; safe here since we don't use
    # the new value anywhere else in this same migration.
    op.execute("ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'cheque'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('method', payment_method_enum, nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cheque_number', sa.String(), nullable=True),
    sa.Column('cheque_date', sa.Date(), nullable=True),
    sa.Column('issued_branch', sa.String(), nullable=True),
    sa.Column('cheque_status', cheque_status_enum, nullable=True),
    sa.Column('cheque_deposit_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_payments_id'), 'purchase_payments', ['id'], unique=False)
    op.create_table('delivery_challans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challan_number', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('bill_type', delivery_challan_bill_type_enum, nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('transporter_name', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_challans_challan_number'), 'delivery_challans', ['challan_number'], unique=True)
    op.create_index(op.f('ix_delivery_challans_id'), 'delivery_challans', ['id'], unique=False)
    op.add_column('job_cards', sa.Column('order_taken_by_id', sa.Integer(), nullable=True))
    op.add_column('job_cards', sa.Column('rubber_stamp_by_id', sa.Integer(), nullable=True))
    op.add_column('job_cards', sa.Column('numbering_by_id', sa.Integer(), nullable=True))
    op.add_column('job_cards', sa.Column('binding_by_id', sa.Integer(), nullable=True))
    op.add_column('job_cards', sa.Column('proof_verified_customer', sa.DateTime(), nullable=True))
    op.add_column('job_cards', sa.Column('proof_verified_press_id', sa.Integer(), nullable=True))
    op.add_column('job_cards', sa.Column('proof_verified_press_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'job_cards', 'users', ['order_taken_by_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'users', ['numbering_by_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'users', ['proof_verified_press_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'users', ['rubber_stamp_by_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'users', ['binding_by_id'], ['id'])
    op.add_column('payments', sa.Column('cheque_number', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('cheque_date', sa.Date(), nullable=True))
    op.add_column('payments', sa.Column('issued_branch', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('cheque_status', cheque_status_enum, nullable=True))
    op.add_column('payments', sa.Column('cheque_deposit_date', sa.Date(), nullable=True))
    op.add_column('purchases', sa.Column('amount_paid', sa.Float(), server_default='0', nullable=False))
    op.add_column('purchases', sa.Column('status', purchase_payment_status_enum, server_default='unpaid', nullable=False))
    op.add_column('quotations', sa.Column('document_type', document_type_enum, server_default='quotation', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'document_type')
    op.drop_column('purchases', 'status')
    op.drop_column('purchases', 'amount_paid')
    op.drop_column('payments', 'cheque_deposit_date')
    op.drop_column('payments', 'cheque_status')
    op.drop_column('payments', 'issued_branch')
    op.drop_column('payments', 'cheque_date')
    op.drop_column('payments', 'cheque_number')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_column('job_cards', 'proof_verified_press_at')
    op.drop_column('job_cards', 'proof_verified_press_id')
    op.drop_column('job_cards', 'proof_verified_customer')
    op.drop_column('job_cards', 'binding_by_id')
    op.drop_column('job_cards', 'numbering_by_id')
    op.drop_column('job_cards', 'rubber_stamp_by_id')
    op.drop_column('job_cards', 'order_taken_by_id')
    op.drop_index(op.f('ix_delivery_challans_id'), table_name='delivery_challans')
    op.drop_index(op.f('ix_delivery_challans_challan_number'), table_name='delivery_challans')
    op.drop_table('delivery_challans')
    op.drop_index(op.f('ix_purchase_payments_id'), table_name='purchase_payments')
    op.drop_table('purchase_payments')
    # ### end Alembic commands ###

    bind = op.get_bind()
    delivery_challan_bill_type_enum.drop(bind, checkfirst=True)
    document_type_enum.drop(bind, checkfirst=True)
    purchase_payment_status_enum.drop(bind, checkfirst=True)
    cheque_status_enum.drop(bind, checkfirst=True)
