"""Add delivery date/time to quotations, job card comments, nullable customer phone

Revision ID: dd361ed76923
Revises: f0925ee52b7a
Create Date: 2026-07-31 03:10:09.769238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd361ed76923'
down_revision: Union[str, Sequence[str], None] = 'f0925ee52b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_card_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_card_comments_id'), 'job_card_comments', ['id'], unique=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('quotations', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('quotations', sa.Column('delivery_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'delivery_time')
    op.drop_column('quotations', 'delivery_date')
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_job_card_comments_id'), table_name='job_card_comments')
    op.drop_table('job_card_comments')
    # ### end Alembic commands ###
