"""Add spec_notes to quotation_items and invoice_items

Revision ID: f0925ee52b7a
Revises: 10127f091907
Create Date: 2026-07-31 02:01:24.973353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0925ee52b7a'
down_revision: Union[str, Sequence[str], None] = '10127f091907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('spec_notes', sa.String(), nullable=True))
    op.add_column('quotation_items', sa.Column('spec_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_items', 'spec_notes')
    op.drop_column('invoice_items', 'spec_notes')
    # ### end Alembic commands ###
