"""Add product and pricing masters tables

Revision ID: f73730ecb23c
Revises: 7dd0b48d2289
Create Date: 2026-07-28 09:14:09.679459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73730ecb23c'
down_revision: Union[str, Sequence[str], None] = '7dd0b48d2289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binding_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('extra_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binding_types_id'), 'binding_types', ['id'], unique=False)
    op.create_index(op.f('ix_binding_types_name'), 'binding_types', ['name'], unique=True)
    op.create_table('colours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colours_id'), 'colours', ['id'], unique=False)
    op.create_index(op.f('ix_colours_name'), 'colours', ['name'], unique=True)
    op.create_table('foiling_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('extra_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foiling_types_id'), 'foiling_types', ['id'], unique=False)
    op.create_index(op.f('ix_foiling_types_name'), 'foiling_types', ['name'], unique=True)
    op.create_table('gsms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsms_id'), 'gsms', ['id'], unique=False)
    op.create_index(op.f('ix_gsms_name'), 'gsms', ['name'], unique=True)
    op.create_table('lamination_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('extra_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lamination_types_id'), 'lamination_types', ['id'], unique=False)
    op.create_index(op.f('ix_lamination_types_name'), 'lamination_types', ['name'], unique=True)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_name'), 'machines', ['name'], unique=True)
    op.create_table('paper_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_types_id'), 'paper_types', ['id'], unique=False)
    op.create_index(op.f('ix_paper_types_name'), 'paper_types', ['name'], unique=True)
    op.create_table('printing_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printing_types_id'), 'printing_types', ['id'], unique=False)
    op.create_index(op.f('ix_printing_types_name'), 'printing_types', ['name'], unique=True)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sizes_id'), 'sizes', ['id'], unique=False)
    op.create_index(op.f('ix_sizes_name'), 'sizes', ['name'], unique=True)
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rate_percent', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxes_id'), 'taxes', ['id'], unique=False)
    op.create_index(op.f('ix_taxes_name'), 'taxes', ['name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('paper_type_id', sa.Integer(), nullable=True),
    sa.Column('gsm_id', sa.Integer(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.Column('colour_id', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colour_id'], ['colours.id'], ),
    sa.ForeignKeyConstraint(['gsm_id'], ['gsms.id'], ),
    sa.ForeignKeyConstraint(['paper_type_id'], ['paper_types.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_id'), 'pricing_rules', ['id'], unique=False)
    op.create_index('ix_pricing_rules_lookup', 'pricing_rules', ['product_id', 'paper_type_id', 'gsm_id', 'size_id', 'colour_id'], unique=False)
    # ### end Alembic commands ###

    taxes = sa.table(
        'taxes',
        sa.column('name', sa.String),
        sa.column('rate_percent', sa.Float),
        sa.column('is_default', sa.Boolean),
        sa.column('is_active', sa.Boolean),
    )
    op.bulk_insert(taxes, [
        {'name': 'GST 18%', 'rate_percent': 18.0, 'is_default': True, 'is_active': True},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_rules_lookup', table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_taxes_name'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_id'), table_name='taxes')
    op.drop_table('taxes')
    op.drop_index(op.f('ix_sizes_name'), table_name='sizes')
    op.drop_index(op.f('ix_sizes_id'), table_name='sizes')
    op.drop_table('sizes')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_printing_types_name'), table_name='printing_types')
    op.drop_index(op.f('ix_printing_types_id'), table_name='printing_types')
    op.drop_table('printing_types')
    op.drop_index(op.f('ix_paper_types_name'), table_name='paper_types')
    op.drop_index(op.f('ix_paper_types_id'), table_name='paper_types')
    op.drop_table('paper_types')
    op.drop_index(op.f('ix_machines_name'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_lamination_types_name'), table_name='lamination_types')
    op.drop_index(op.f('ix_lamination_types_id'), table_name='lamination_types')
    op.drop_table('lamination_types')
    op.drop_index(op.f('ix_gsms_name'), table_name='gsms')
    op.drop_index(op.f('ix_gsms_id'), table_name='gsms')
    op.drop_table('gsms')
    op.drop_index(op.f('ix_foiling_types_name'), table_name='foiling_types')
    op.drop_index(op.f('ix_foiling_types_id'), table_name='foiling_types')
    op.drop_table('foiling_types')
    op.drop_index(op.f('ix_colours_name'), table_name='colours')
    op.drop_index(op.f('ix_colours_id'), table_name='colours')
    op.drop_table('colours')
    op.drop_index(op.f('ix_binding_types_name'), table_name='binding_types')
    op.drop_index(op.f('ix_binding_types_id'), table_name='binding_types')
    op.drop_table('binding_types')
    # ### end Alembic commands ###
