"""add order_type to quotations and invoices

Revision ID: fad51d6558ec
Revises: d25026cfb851
Create Date: 2026-07-31 10:18:09.040234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad51d6558ec'
down_revision: Union[str, Sequence[str], None] = 'd25026cfb851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


order_type_enum = sa.Enum('offline', 'online', name='ordertype')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column doesn't create the backing PG enum type by itself - must create it explicitly first.
    order_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('invoices', sa.Column('order_type', order_type_enum, server_default='offline', nullable=False))
    op.add_column('quotations', sa.Column('order_type', order_type_enum, server_default='offline', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'order_type')
    op.drop_column('invoices', 'order_type')
    # ### end Alembic commands ###
    order_type_enum.drop(op.get_bind(), checkfirst=True)
