"""Add job_cards table

Revision ID: fe504772f767
Revises: ac9cb0fab2e1
Create Date: 2026-07-28 09:26:49.310980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe504772f767'
down_revision: Union[str, Sequence[str], None] = 'ac9cb0fab2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(), nullable=True),
    sa.Column('quotation_item_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('designer_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='jobcardpriority'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'design', 'approval', 'printing', 'binding', 'packing', 'delivered', name='jobcardstatus'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['designer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_item_id')
    )
    op.create_index(op.f('ix_job_cards_id'), 'job_cards', ['id'], unique=False)
    op.create_index(op.f('ix_job_cards_job_number'), 'job_cards', ['job_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_cards_job_number'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_id'), table_name='job_cards')
    op.drop_table('job_cards')
    # ### end Alembic commands ###
